import { useEffect } from "react";
import { FilledButton } from "../../components/common/Buttons/FilledButton";
import { NoBGButton } from "../../components/common/Buttons/NoBGButton";
import { DigitalClock } from "../../components/Home/DigitalClock";
import { ConfigActions, useConfig } from "../../context/ConfigContext";
import { SocialMedias } from "../../helpers/SocialMedia";
import * as C from "./styles";

const resumeLink =
  "https://drive.google.com/drive/folders/1UAOnXYuI-NMZW0B8O1Z3PDIG7_yoDi9S?usp=share_link";

const PortugueseDesc = () => {
  return (
    <>
      <C.Content>
        Meu nome é <span>Thiago Silva</span>, também conhecido como{" "}
        <span>Fang</span>, sou apaixonado por tecnologia desde pequeno, meu
        primeiro contato com programação foi no ensino fundamental onde tentei
        criar a minha própria versão de um jogo que eu jogava muito.
      </C.Content>
      <C.Content>
        Após me formar como designer, tive mais contato com a parte de
        programação e percebi era o que eu realmente amava, é o espaço onde
        posso sempre{" "}
        <span>aprender coisas novas e sentir que faço parte do futuro</span>,
        escolhi atuar no Front-End pois mistura programação com design, procuro
        me desenvolver todos os dias, conhecer novas tecnologias e recursos
        deste âmbito profissional.
      </C.Content>
    </>
  );
};

const EnglishDesc = () => {
  return (
    <>
      <C.Content>
        My name is <span>Thiago Silva</span>, also known as <span>Fang</span>, I
        have been passionate about technology since I was young, my first
        contact with programming was in elementary school where I tried to
        create my own version of a game I used to play a lot.
      </C.Content>
      <C.Content>
        After graduating as a designer, I had more contact with the programming
        part and realized that it was what I really loved,{" "}
        <span>
          it's the space where I can always learn new things and feel that I am
          part of the future
        </span>
        , I chose to work in Front-End because it combines programming with
        design, I strive to develop myself every day, learn about new
        technologies and resources in this professional field.
      </C.Content>
    </>
  );
};

export const AboutMe = () => {
  const { state, dispatch } = useConfig();

  const openLink = (link: string) => {
    window.open(link, "_blank");
  };

  useEffect(() => {
    dispatch({ type: ConfigActions.setInitialLoading, payload: false });
  }, []);

  return (
    <C.Container>
      <DigitalClock />
      <C.MainContent>
        <C.ImageArea
          warning={
            state.language === "pt"
              ? "Imagem gerada por IA"
              : "Image generated by AI."
          }
        >
          <C.SocialMedia>
            {SocialMedias.map((item, key) => (
              <C.SocialIcon
                onClick={() => openLink(item.link)}
                key={key}
                className={item.icon}
              ></C.SocialIcon>
            ))}
          </C.SocialMedia>
        </C.ImageArea>
        <C.TextArea>
          <C.Title>
            {state.language === "pt" ? "Quem sou eu?" : "Who am i?"}
          </C.Title>
          {state.language === "pt" && <PortugueseDesc />}
          {state.language === "en" && <EnglishDesc />}
          <C.ButtonsArea>
            <FilledButton
              icon="ri-download-line"
              isLink
              title={state.language === "pt" ? "Curriculo" : "Resume"}
              to={resumeLink}
              id="AboutCurriculumBtn"
            />
            <NoBGButton
              icon="ri-arrow-right-s-fill"
              title={state.language === "pt" ? "Meus Projetos" : "My Projects"}
              to="/projects"
              id="AboutProjectBtn"
              isLink={false}
            />
          </C.ButtonsArea>
        </C.TextArea>
      </C.MainContent>
    </C.Container>
  );
};
